feat: add new sas file to New File... (resolves #811)
sassoftware/vscode-sas-extension pull request #812
Opened 2024-02-07 07:37 UTC by scnjdl

**Summary**
support create a new sas file from New File... in File menu (resolves #811)

**Testing**
Click New File... in File menu
Select SAS File SAS from dropdown list
A untitled sas file opened in active window

2024-02-13 13:21 UTC, smorrisj commented
Thanks for adding this! See comment above.

2024-02-22 16:54 UTC, scottdover reviewed
I think this looks good, but I'll leave @smorrisj to +1 since he left a comment

2024-02-22 17:03 UTC, smorrisj requested changes

2024-03-01 02:32 UTC, scnjdl commented on client/src/node/extension.ts
> +      await window.showTextDocument(
Done

2024-03-04 02:38 UTC, scnwwu approved these changes

2024-03-04 03:03 UTC, scnjdl commented
@smorrisj I have updated code, can you approve? Thank you.

2024-03-07 06:43 UTC, tianliang657 commented
I've finished this new feature functional and I18N testing, looks good to me. Approving.

2024-03-07 06:56 UTC, merged

2024-03-08 06:45 UTC, tianliang657 commented
This new feature is working fine in the main branch.